// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Produnet.WebBFF.Prueba.Produnet.WebBFF.Prueba.Infraestructura.Data.Context;

#nullable disable

namespace Produnet.WebBFF.Prueba.Migrations
{
    [DbContext(typeof(AplicacionDbContext))]
    partial class AplicacionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Produnet.WebBFF.Prueba.Produnet.WebBFF.Prueba.Dominio.PeriodoInactividad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SesionUsuarioId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SesionUsuarioId");

                    b.ToTable("PeriodosInactividad");
                });

            modelBuilder.Entity("Produnet.WebBFF.Prueba.Produnet.WebBFF.Prueba.Dominio.SesionUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("HoraFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HoraInicio")
                        .HasColumnType("datetime2");

                    b.Property<string>("NombreEquipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SesionesUsuario");
                });

            modelBuilder.Entity("Produnet.WebBFF.Prueba.Produnet.WebBFF.Prueba.Dominio.PeriodoInactividad", b =>
                {
                    b.HasOne("Produnet.WebBFF.Prueba.Produnet.WebBFF.Prueba.Dominio.SesionUsuario", "SesionUsuario")
                        .WithMany("PeriodosInactividad")
                        .HasForeignKey("SesionUsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SesionUsuario");
                });

            modelBuilder.Entity("Produnet.WebBFF.Prueba.Produnet.WebBFF.Prueba.Dominio.SesionUsuario", b =>
                {
                    b.Navigation("PeriodosInactividad");
                });
#pragma warning restore 612, 618
        }
    }
}
